name: deploy on gh pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Run npm install
        run: npm install

      - name: Run npm run build
        run: npm run build

      - name: Remove .git
        run: rm -r .git

      - name: Copy files to browser
        run: cp ./dist/3rdpartylicenses.txt ./dist/browser

      - name: run pwd
        run: pwd

      - name: Make deploy file and repo
        run: |
          mkdir -p ./deploy
          rm -rf ./deploy/*
          git --global config user.name "GitHub Action"
          git --global config user.email "action@github.com"
          git --global config github.token ${{ secrets.GITHUB_TOKEN }}
          git -C ./deploy clone https://github.com/FaboBorgesLima/web-dev-utils.git
          git -C ./deploy checkout origin/origin/gh-pages
          git -C ./deploy rm -rf .
          git -C ./deploy clean -fxd

      - name: Copy deploy
        run: cp ./dist/browser ./deploy

      - name: Init git repo on browser
        run: |
          cd deploy
          git add .
          git commit -m "deploy-to-gh-pages"
          git push
