name: deploy on gh pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build main
        run: |
          cd main
          npm install
          npm run build
          cd ..

      - name: Clear gh-pages
        run: |
          cd gh-pages
          git rm -r *
          cd ..

      - name: Copy files to gh-pages
        run: |
          cp main/dist/3rdpartylicenses.txt main/dist/browser
          cp main/dist/browser/* gh-pages/

      - name: Commit and push from gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bot"
          git push
